source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Spectrometer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spectrometer
    pod 'VerticalSlider'
    pod 'GMStepper'
    pod 'SwiftMessages' 
    pod 'NVActivityIndicatorView'
pod 'EasySocialButton'
pod 'Charts'
end

